default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info

stages:
  - build

build-image:
  stage: build

  rules:
    - if: $CI_COMMIT_TAG
      when: manual

  parallel:
    matrix:
      - APP_NAME: [user, order, wallet, market, notify, board]
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_FORCE_HTTPS: "true"
    IMAGE_NAME: $CI_REGISTRY_IMAGE/$APP_NAME
    IMAGE_TAG: $IMAGE_NAME:$CI_COMMIT_REF_NAME
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --target=image --build-arg="APP_NAME=$APP_NAME" -f=docker/Dockerfile -t=$IMAGE_TAG .
    - docker tag $IMAGE_TAG $IMAGE_NAME:latest
    - docker push --all-tags $IMAGE_NAME
