topic:
  user:
    created: user.created

  order:
    withdraw:
      created: order.withdraw.created
    deposit:
      created: order.deposit.created
    #spot:
    #  created: order.spot.created

  wallet:
    transaction: wallet.transaction
